function s = labspec()
%LABSPEC  Single source of truth for the test lab.
%   Constants, the five requirements, the five scenarios and every input
%   parameter with its documented range.  Ported from lab_spec.py; the ranges
%   here and the ranges LABVALIDATE enforces cannot drift apart because they
%   are the same table.

% --- geometry facts, not tunables ---------------------------------------
s.ROBOT_RADIUS   = 0.037;    % e-puck body radius [m]
s.WHEEL_RADIUS   = 0.0205;   % e-puck wheel radius [m]
s.TRACK_WIDTH    = 0.052;    % e-puck axle length [m]
s.MAX_WHEEL_SPEED= 6.28;     % motor limit [rad/s]
s.ARENA_HALF     = 0.99;     % inner face of the arena wall [m]
s.OBSTACLE_RADIUS= 0.075;    % free-standing cylinders [m]
s.WALL_THICKNESS = 0.05;     % corridor barrier thickness [m]
s.GOAL_TOLERANCE = 0.10;     % centre within this = goal reached [m]
s.SENSOR_RANGE   = 0.50;     % time-of-flight full scale [m]
s.SENSOR_ANGLES  = [-25 0 25]*pi/180;   % three beams, forward and +/-25 deg

% Deliberate: the sensors saturate at short range, so a clearance requirement
% much larger could not be met by reactive avoidance at all and every obstacle
% test would fail for the same uninteresting reason.
s.MIN_CLEARANCE_REQUIRED = 0.03;

% --- requirements --------------------------------------------------------
s.requirements = { ...
 'REQ-1', sprintf('The robot shall reach the target position (centre within %.2f m) before the maximum execution time elapses.', s.GOAL_TOLERANCE); ...
 'REQ-2', 'The robot shall not collide with any obstacle or arena wall.'; ...
 'REQ-3', sprintf('The robot shall maintain a clearance of at least %.2f m from every obstacle and arena wall for the whole run.', s.MIN_CLEARANCE_REQUIRED); ...
 'REQ-4', 'The robot shall remain inside the arena at all times.'; ...
 'REQ-5', 'The system shall accept only documented input ranges and shall reject any out-of-range or malformed input without running a test.'};

% --- scenarios -----------------------------------------------------------
sc = @(k,l,d,e) struct('key',k,'label',l,'description',d,'extra',{e});
s.scenarios = [ ...
 sc('OPEN_FIELD','Open field (no obstacles)', ...
    'Empty arena. Isolates the navigation and timing behaviour.',{{}}); ...
 sc('SINGLE_OBSTACLE','Single obstacle', ...
    'One 0.15 m diameter cylinder at a position you choose.',{{'obstacle_x','obstacle_y'}}); ...
 sc('CORRIDOR','Corridor / narrow gap', ...
    'A barrier across the arena with a gap of the width you choose.',{{'corridor_width'}}); ...
 sc('DOGLEG','Dogleg', ...
    'Two offset barriers that force an S-shaped path.',{{}}); ...
 sc('CLUTTER','Clutter (6 obstacles)', ...
    'Six fixed obstacles scattered across the arena.',{{}})];

% --- input parameters ----------------------------------------------------
p = @(k,kind,def,mn,mx,st,lbl,unit,help,ch) struct('key',k,'kind',kind, ...
    'default',def,'min',mn,'max',mx,'step',st,'label',lbl,'unit',unit, ...
    'help',help,'choices',{ch});

s.parameters = [ ...
 p('scenario','enum','SINGLE_OBSTACLE',0,0,0,'Scenario','', ...
   'Which preconfigured arena layout to test against.', {{s.scenarios.key}}); ...
 p('speed','float',5.5,0.5,s.MAX_WHEEL_SPEED,0.01,'Wheel speed','rad/s', ...
   sprintf('Cruise wheel speed. %.2f rad/s is the motor limit (%.3f m/s).', ...
   s.MAX_WHEEL_SPEED, s.MAX_WHEEL_SPEED*s.WHEEL_RADIUS), {{}}); ...
 p('start_x','float',-0.80,-0.85,0.85,0.01,'Start X','m','Initial robot position, X axis.',{{}}); ...
 p('start_y','float',-0.80,-0.85,0.85,0.01,'Start Y','m','Initial robot position, Y axis.',{{}}); ...
 p('start_heading_deg','float',45,-180,180,1,'Start heading','deg', ...
   'Initial orientation. 0 deg faces +X, 90 deg faces +Y.',{{}}); ...
 p('goal_x','float',0.80,-0.85,0.85,0.01,'Goal X','m','Target position, X axis.',{{}}); ...
 p('goal_y','float',0.80,-0.85,0.85,0.01,'Goal Y','m','Target position, Y axis.',{{}}); ...
 p('obstacle_x','float',0,-0.85,0.85,0.01,'Obstacle X','m', ...
   'SINGLE_OBSTACLE only: centre of the cylinder, X axis.',{{}}); ...
 p('obstacle_y','float',0,-0.85,0.85,0.01,'Obstacle Y','m', ...
   'SINGLE_OBSTACLE only: centre of the cylinder, Y axis.',{{}}); ...
 p('corridor_width','float',0.40,0.15,0.90,0.01,'Corridor width','m', ...
   sprintf('CORRIDOR only: width of the gap. The robot is %.3f m wide.',2*s.ROBOT_RADIUS),{{}}); ...
 p('sensor_noise','float',0,0,0.50,0.01,'Sensor noise','fraction', ...
   'Relative Gaussian noise on every range reading. Reproducible for a given seed.',{{}}); ...
 p('max_time','float',30,5,120,1,'Max execution time','s', ...
   'Simulated seconds allowed before the run is declared a timeout.',{{}}); ...
 p('seed','int',1,1,999999,1,'Noise seed','', ...
   'Seed of the noise generator. The same seed always reproduces the same run.',{{}})];

s.defaults = struct();
for i = 1:numel(s.parameters)
    s.defaults.(s.parameters(i).key) = s.parameters(i).default;
end
end
