#!/usr/bin/env python3
"""Turn a matrix run into docs/MEASURED_BOUNDARIES.md.

    python3 tools/run_matrix.py --out results/matrix
    python3 tools/make_boundary_report.py

Keeping the report generated rather than hand-written means the numbers the
students and the instructor read can never drift away from what the simulator
actually does.
"""

import argparse
import collections
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PROJECT = os.path.dirname(HERE)


def outcome(r):
    if r["goal_reached"] and r["verdict"] == "FAIL":
        return "goal reached, clearance too small"
    if r["goal_reached"]:
        return "goal reached"
    if r["collision"]:
        return "collision with " + str(r["collision_object"])
    if r["left_arena"]:
        return "left arena"
    return "timed out"


def build(results):
    lines = []
    add = lines.append

    def rows(pred):
        return [r for r in results if r["verdict"] != "REJECTED" and pred(r)]

    add("# Measured behaviour of the reference controller\n")
    add("Generated by `python3 tools/run_matrix.py` from "
        "`tools/validation_matrix.json`, then `python3 tools/make_boundary_report.py`. "
        "Every number below came out of an actual headless Webots run of this "
        "project; nothing here is an estimate. Regenerate it after any change to "
        "the controller, the world, or the requirements.\n")

    counts = collections.Counter(r["verdict"] for r in results)
    add("## Summary\n")
    add("| Outcome | Cases |")
    add("|---|---|")
    for key in ("PASS", "FAIL", "REJECTED"):
        add("| %s | %d |" % (key, counts.get(key, 0)))
    add("| **Total** | **%d** |\n" % len(results))

    def table(title, note, selection, key, key_name, fmt):
        add("## " + title + "\n")
        if note:
            add(note + "\n")
        add("| " + key_name + " | Verdict | Completion time (s) | "
            "Min clearance (m) | Outcome |")
        add("|---|---|---|---|---|")
        for r in selection:
            add("| %s | %s | %.2f | %.4f | %s |"
                % (fmt % r["params"][key], r["verdict"], r["completion_time"],
                   r["min_clearance"], outcome(r)))
        add("")

    table(
        "Wheel speed, open field, 30 s limit",
        "Two boundaries live on this axis. Below roughly 3.7 rad/s the robot "
        "cannot cover the 2.26 m diagonal inside the 30 s limit. The upper end "
        "of the range is comfortable in an empty arena; it is the obstacle "
        "scenarios that punish speed.",
        sorted(rows(lambda r: r["label"].startswith(("BVA-speed", "EP-"))),
               key=lambda r: r["params"]["speed"]),
        "speed", "Speed (rad/s)", "%.2f")

    table(
        "Corridor width, 4.0 rad/s, 60 s limit",
        "The analytic lower bound is 0.134 m: the robot is 0.074 m wide and "
        "REQ-3 asks for 0.03 m on each side. The controller's own limit sits "
        "well above that, and the failure *mode* changes as the gap narrows - "
        "from a clearance violation to an outright failure to find the gap.",
        sorted(rows(lambda r: r["label"].startswith("BVA-corr")),
               key=lambda r: r["params"]["corridor_width"]),
        "corridor_width", "Corridor width (m)", "%.2f")

    table(
        "Sensor noise, single obstacle, 4.5 rad/s, 45 s limit",
        "Noise is injected into the time-of-flight readings from a seeded "
        "generator, so each of these runs reproduces exactly.",
        sorted(rows(lambda r: r["label"].startswith("ROB-noise")),
               key=lambda r: r["params"]["sensor_noise"]),
        "sensor_noise", "Noise (fraction)", "%.2f")

    add("## Scenario difficulty\n")
    add("| Case | Speed (rad/s) | Verdict | Completion time (s) | Min clearance (m) |")
    add("|---|---|---|---|---|")
    for r in rows(lambda r: r["label"].startswith("SC-")):
        add("| %s | %.2f | %s | %.2f | %.4f |"
            % (r["label"], r["params"]["speed"], r["verdict"],
               r["completion_time"], r["min_clearance"]))
    add("")
    add("The dogleg and the cluttered arena are where a purely reactive "
        "controller is weakest, and the relationship with speed is not "
        "monotonic: the slow runs exhaust the time budget negotiating "
        "obstacles while the fast runs get through. That non-monotonicity is "
        "worth showing students - it is exactly why single-point testing is "
        "not enough.\n")

    add("## Rejected inputs (REQ-5)\n")
    add("| Case | Message |")
    add("|---|---|")
    for r in results:
        if r["verdict"] == "REJECTED":
            add("| %s | %s |" % (r["label"], " ".join(r.get("errors", []))))
    add("")

    add("## Repeatability\n")
    groups = {}
    for r in results:
        if "#" in r.get("label", ""):
            groups.setdefault(r["label"].split("#")[0], []).append(r)
    add("| Group | Runs | Verdict | Max spread, completion time (s) | "
        "Max spread, min clearance (m) | Max spread, path length (m) |")
    add("|---|---|---|---|---|---|")
    for name, runs in sorted(groups.items()):
        first = runs[0]

        def spread(key):
            return max(abs(run[key] - first[key]) for run in runs)

        add("| %s | %d | %s | %.4f | %.4f | %.4f |"
            % (name, len(runs),
               "stable" if all(x["verdict"] == first["verdict"] for x in runs)
               else "CHANGED",
               spread("completion_time"), spread("min_clearance"),
               spread("path_length")))
    add("")
    add("The verdict, and every discrete outcome behind it (goal reached, "
        "collision, left arena, timed out), reproduces exactly. Continuous "
        "measurements reproduce to within a fraction of a millimetre of "
        "clearance and a couple of millimetres of path length over a 90 s run "
        "through the cluttered arena: a long trajectory among obstacles is "
        "chaotic and the physics engine is not bit-exact across a whole "
        "session. `tools/run_matrix.py` enforces those tolerances, so a real "
        "regression cannot hide inside them.\n")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--results",
                        default=os.path.join(PROJECT, "results", "matrix",
                                             "results.json"))
    parser.add_argument("--out",
                        default=os.path.join(PROJECT, "docs",
                                             "MEASURED_BOUNDARIES.md"))
    args = parser.parse_args()

    if not os.path.exists(args.results):
        sys.exit("No results at %s - run tools/run_matrix.py first."
                 % args.results)
    with open(args.results) as handle:
        results = json.load(handle)
    with open(args.out, "w") as handle:
        handle.write(build(results))
    print("Wrote", args.out)


if __name__ == "__main__":
    main()
